
format = """
[â•­â”€](white)$username$hostname$shell$directory$conda$container$docker_context$git_branch$git_state$git_status$git_commit$git_metrics$aws$c$cpp$cmake$nodejs$python$java$golang$package$cmd_duration
[â•°â”€](white)$character"""


# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[â¯](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
error_symbol = '[â¯](bold red)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false
symbol = "ğŸ“¦ "
format = "[$symbol$version ]($style)"

[nodejs]
format = '[$symbol($version )]($style)'

[python]
symbol = 'ğŸ '
format = '[${symbol}${pyenv_prefix}(${version} ) (\($virtualenv\) )]($style)'

[golang]
format = '[$symbol($version )]($style)'

[java]
format = '[${symbol}(${version} )]($style)'

[docker_context]
format = '[ğŸ‹ $context ](blue bold)'

[username]
style_user = 'green bold'
style_root = 'red bold'
show_always = true
format = '[$user]($style)@'

[hostname]
ssh_only = false
format = '[$hostname]($style) '

[sudo]
disabled=false

[os]
disabled=false

[os.symbols]
Gentoo = "ó°£¨ "
Arch = "ó°£‡ "

[git_branch]
style="yellow bold"

[git_metrics]
disabled=false
added_style = 'bold blue'
deleted_style = 'bold red'
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )' 

[shell]
disabled=false
nu_indicator="ó°Ÿ† nu"
zsh_indicator="ï„µ zsh"
bash_indicator="îš‘ bash"
fish_indicator="ó°ˆº fish"
unknown_indicator="ó±šŸ tf is ts?"
powershell_indicator="ó°¨Š pwsh"
cmd_indicator="ï„  cmd"
style="purple bold"
format = "[$indicator]($style) "

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = "took [$duration]($style) "

